name: Build & Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: chmod +x gradlew

      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -alias almuadhin \
            -keyalg RSA -keysize 2048 \
            -validity 9125 \
            -keystore almuadhin.jks \
            -storepass almuadhin123 \
            -keypass almuadhin123 \
            -dname "CN=ALmuadhin,O=Islamic,C=EG" \
            -noprompt

      - name: Build APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/almuadhin.jks \
            -Pandroid.injected.signing.store.password=almuadhin123 \
            -Pandroid.injected.signing.key.alias=almuadhin \
            -Pandroid.injected.signing.key.password=almuadhin123

      - name: Create Release with APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          name: "مؤذن محمد عبد العظيم - إصدار ${{ github.run_number }}"
          files: app/build/outputs/apk/release/*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
